---
user: Username Here
password: pa55w0rd h3r3
wiki: communitytest (replace this with your wiki's URL, e.g. The My Little Pony wiki at http://mlp.wikia.com would have 'mlp' here)

discord:
  channel: 
  id: 
  token: 
